[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino

; Hardware fixes for your specific ESP-01 module
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
board_build.f_flash = 40000000L

; Communication settings
monitor_speed = 9600
upload_speed = 115200