[env:uno]
platform = atmelavr           ; The platform for standard Arduinos
board = uno                   ; The board type (Change to 'nanoatmega328' if using a Nano)
framework = arduino

; Serial Monitor settings
monitor_speed = 9600          ; Matches Serial.begin(9600) in your code

; Upload settings
; usually you don't need to specify upload_speed for Arduino, 
; PlatformIO detects it automatically.